import { StudyCircle } from './types';

export const CIRCLES: StudyCircle[] = [
  // ─── 1 ────────────────────────────────────────────────────────────────────
  {
    id: 'hsc-physics-breakers',
    name: 'HSC Physics Breakers',
    tagline: 'পদার্থবিজ্ঞান ভয় নেই — একসাথে ভাঙব',
    description:
      'HSC পদার্থবিজ্ঞানের সবচেয়ে কঠিন অধ্যায়গুলো — তড়িৎ, তরঙ্গ, আধুনিক পদার্থবিজ্ঞান — একসাথে আলোচনা করে বোঝার গ্রুপ। প্রতিটি সেশনে একজন কনসেপ্ট ব্যাখ্যা করে, বাকিরা প্রশ্ন করে। বোর্ড প্রশ্ন বিশ্লেষণ ও MCQ দ্রুত সমাধান করার উপর ফোকাস।',
    studyApproach: [
      'একজন লিড করে, বাকিরা প্রশ্ন করে',
      'প্রতি সেশনে ১টি অধ্যায় + ১৫টি বোর্ড প্রশ্ন',
      'সপ্তাহান্তে mock MCQ battle',
    ],
    rules: [
      'প্রতিদিন অন্তত ৩০ মিনিট পড়তে হবে',
      'সেশনে না আসলে কারণ জানাতে হবে',
      'প্রশ্ন করতে লজ্জা নেই — সব প্রশ্ন welcome',
    ],
    tags: ['HSC', 'পদার্থবিজ্ঞান', 'বোর্ড প্রশ্ন', 'MCQ', 'রাতের সেশন'],
    class: ['class11', 'class12'],
    goals: ['exam_prep', 'weak_subject', 'admission_prep'],
    subjects: ['physics', 'math'],
    timeSlot: ['evening', 'night'],
    sharedGoal: 'HSC পদার্থবিজ্ঞান ১ম পত্র শেষ করা — ৩০ দিনে',
    nextSession: 'আজ রাত ৯টায়',
    weeklyTarget: '৩টি অধ্যায় + ৫০টি MCQ',
    coverEmoji: '⚡',
    color: '#6C3CE1',
    maxMembers: 12,
    weeklyStreak: 6,
    founded: '৬ সপ্তাহ আগে',
    language: 'bangla',
    milestones: [
      { label: '১ম অধ্যায় সম্পন্ন', achieved: true, emoji: '✅' },
      { label: 'প্রথম mock test', achieved: true, emoji: '✅' },
      { label: 'সব তরঙ্গ অধ্যায় শেষ', achieved: false, emoji: '🎯' },
      { label: 'ফাইনাল মডেল টেস্ট', achieved: false, emoji: '🏆' },
    ],
    members: [
      { id: 'm1', name: 'Rafiq Ahmed', avatar: '👨‍🎓', class: 'class12', lastActive: '২ ঘন্টা আগে', streak: 12, role: 'captain' },
      { id: 'm2', name: 'Nadia Islam', avatar: '👩‍🎓', class: 'class12', lastActive: '৩০ মিনিট আগে', streak: 8, role: 'member' },
      { id: 'm3', name: 'Tariq Hossain', avatar: '🧑‍🎓', class: 'class11', lastActive: '১ ঘন্টা আগে', streak: 5, role: 'member' },
      { id: 'm4', name: 'Suma Akter', avatar: '👩‍💻', class: 'class12', lastActive: 'এইমাত্র', streak: 21, role: 'member' },
      { id: 'm5', name: 'Milon Roy', avatar: '👨‍💻', class: 'class11', lastActive: '৪ ঘন্টা আগে', streak: 3, role: 'member' },
    ],
    activity: [
      { id: 'a1', memberId: 'm4', memberName: 'Suma Akter', avatar: '👩‍💻', type: 'studied', content: 'তড়িৎ চৌম্বকীয় আবেশ অধ্যায় শেষ করলাম', subject: 'physics', timestamp: '১৫ মিনিট আগে', reactions: 5 },
      { id: 'a2', memberId: 'm2', memberName: 'Nadia Islam', avatar: '👩‍🎓', type: 'stuck', content: "Kirchhoff's law-এ আটকে গেছি, কেউ সাহায্য করতে পারবে?", subject: 'physics', timestamp: '৩০ মিনিট আগে', reactions: 3 },
      { id: 'a3', memberId: 'm1', memberName: 'Rafiq Ahmed', avatar: '👨‍🎓', type: 'join_me', content: 'আজ রাত ৯টায় একসাথে পড়ব — আসো!', timestamp: '১ ঘন্টা আগে', reactions: 7 },
      { id: 'a4', memberId: 'm3', memberName: 'Tariq Hossain', avatar: '🧑‍🎓', type: 'completed', content: 'আলোর বিচ্ছুরণ ও বর্ণ অধ্যায়ের সব MCQ শেষ ✅', subject: 'physics', timestamp: '৩ ঘন্টা আগে', reactions: 12 },
      { id: 'a5', memberId: 'm5', memberName: 'Milon Roy', avatar: '👨‍💻', type: 'joined', content: 'এই সার্কেলে যোগ দিয়েছি', timestamp: 'গতকাল', reactions: 4 },
    ],
  },

  // ─── 2 ────────────────────────────────────────────────────────────────────
  {
    id: 'ssc-math-squad',
    name: 'SSC Math Squad',
    tagline: 'গণিত কঠিন না — একসাথে সহজ',
    description:
      'SSC গণিতের বীজগণিত, জ্যামিতি ও ত্রিকোণমিতি নিয়ে যারা ভয়ে আছ তাদের জন্য। প্রতিটি সমস্যা ধাপে ধাপে সমাধান করা হয় যাতে সবাই বুঝতে পারে। কেউ আটকে গেলে গ্রুপ মিলে বের করে — কেউ একা থাকে না।',
    studyApproach: [
      'ধাপে ধাপে সমস্যা সমাধান — কেউ বাদ পড়ে না',
      'প্রতিদিন ৫টি সমস্যার চ্যালেঞ্জ',
      'শুক্রবার সাপ্তাহিক মিনি টেস্ট',
    ],
    rules: [
      'ভুল উত্তর দিলে কেউ হাসবে না — ভুল থেকেই শেখা',
      'প্রতিদিন অন্তত ১টি সমস্যা সমাধান করতে হবে',
      'সাহায্য চাওয়া দুর্বলতা নয় — বুদ্ধিমানের কাজ',
    ],
    tags: ['SSC', 'গণিত', 'বীজগণিত', 'জ্যামিতি', 'বিকালের সেশন'],
    class: ['class9', 'class10'],
    goals: ['exam_prep', 'weak_subject'],
    subjects: ['math', 'ict'],
    timeSlot: ['afternoon', 'evening'],
    sharedGoal: 'SSC গণিত সব অধ্যায় + মডেল টেস্ট',
    nextSession: 'আগামীকাল বিকাল ৫টায়',
    weeklyTarget: 'বীজগণিত অধ্যায় সম্পন্ন + ২টি পরীক্ষা',
    coverEmoji: '📐',
    color: '#E91E8C',
    maxMembers: 15,
    weeklyStreak: 4,
    founded: '৪ সপ্তাহ আগে',
    language: 'bangla',
    milestones: [
      { label: 'সেট ও ফাংশন শেষ', achieved: true, emoji: '✅' },
      { label: 'বীজগণিত সম্পন্ন', achieved: false, emoji: '🎯' },
      { label: 'জ্যামিতি সম্পন্ন', achieved: false, emoji: '🎯' },
      { label: 'ফাইনাল মডেল টেস্ট', achieved: false, emoji: '🏆' },
    ],
    members: [
      { id: 'm6', name: 'Rina Begum', avatar: '👩‍🎓', class: 'class10', lastActive: '১ ঘন্টা আগে', streak: 15, role: 'captain' },
      { id: 'm7', name: 'Karim Uddin', avatar: '👨‍🎓', class: 'class10', lastActive: '৪৫ মিনিট আগে', streak: 9, role: 'member' },
      { id: 'm8', name: 'Puja Das', avatar: '👩‍💻', class: 'class9', lastActive: '২ ঘন্টা আগে', streak: 6, role: 'member' },
      { id: 'm9', name: 'Arif Khan', avatar: '🧑‍🎓', class: 'class10', lastActive: 'এইমাত্র', streak: 18, role: 'member' },
      { id: 'm10', name: 'Shirin Akter', avatar: '👩‍🎓', class: 'class9', lastActive: '৩ ঘন্টা আগে', streak: 4, role: 'member' },
      { id: 'm11', name: 'Babu Mia', avatar: '👨‍💻', class: 'class10', lastActive: '৬ ঘন্টা আগে', streak: 2, role: 'member' },
    ],
    activity: [
      { id: 'b1', memberId: 'm9', memberName: 'Arif Khan', avatar: '🧑‍🎓', type: 'join_me', content: 'এখন বীজগণিত practice করছি — আসো একসাথে', subject: 'math', timestamp: '১০ মিনিট আগে', reactions: 8 },
      { id: 'b2', memberId: 'm6', memberName: 'Rina Begum', avatar: '👩‍🎓', type: 'completed', content: 'ত্রিকোণমিতি অধ্যায় শেষ! ৪৫/৫০ MCQ ✅', subject: 'math', timestamp: '১ ঘন্টা আগে', reactions: 14 },
      { id: 'b3', memberId: 'm8', memberName: 'Puja Das', avatar: '👩‍💻', type: 'stuck', content: 'লগারিদম সমীকরণে সমস্যা হচ্ছে, কেউ বোঝাতে পারবে?', subject: 'math', timestamp: '২ ঘন্টা আগে', reactions: 2 },
      { id: 'b4', memberId: 'm7', memberName: 'Karim Uddin', avatar: '👨‍🎓', type: 'studied', content: 'সেট থিওরি + ফাংশন — দুটো অধ্যায় একদিনে', subject: 'math', timestamp: '৪ ঘন্টা আগে', reactions: 9 },
    ],
  },

  // ─── 3 ────────────────────────────────────────────────────────────────────
  {
    id: 'hsc-biology-stars',
    name: 'HSC Biology Stars',
    tagline: 'জীববিজ্ঞান — মুখস্থ নয়, বোঝো',
    description:
      'মেডিকেল ভর্তি পরীক্ষার জন্য HSC জীববিজ্ঞানের গভীর প্রস্তুতির গ্রুপ। কোষ বিভাজন, সালোকসংশ্লেষণ, শ্বসন, প্রাণী শারীরতত্ত্ব — কনসেপ্ট-ভিত্তিক পড়াশোনা। রট মেমোরাইজেশন নয়, কারণ বুঝে পড়া। সকালের সেশনে সবচেয়ে জটিল টপিক ধরা হয়।',
    studyApproach: [
      'কনসেপ্ট ম্যাপ দিয়ে বোঝানো',
      'প্রতিটি অধ্যায়ের পর ১০টি প্রশ্নোত্তর session',
      'মেডিকেল admission এর previous year questions বিশ্লেষণ',
    ],
    rules: [
      'সকালের সেশন মিস করলে নোট শেয়ার করতে হবে',
      'diagram আঁকার অভ্যাস করতে হবে',
      'শুধু পড়া নয় — বোঝানোর চেষ্টা করতে হবে',
    ],
    tags: ['HSC', 'জীববিজ্ঞান', 'মেডিকেল ভর্তি', 'রসায়ন', 'সকালের সেশন'],
    class: ['class11', 'class12'],
    goals: ['exam_prep', 'weak_subject', 'admission_prep'],
    subjects: ['biology', 'chemistry'],
    timeSlot: ['morning', 'afternoon'],
    sharedGoal: 'মেডিকেল ভর্তি প্রস্তুতি — জীববিজ্ঞান ১ম ও ২য় পত্র',
    nextSession: 'আজ সকাল ৮টায়',
    weeklyTarget: 'কোষ বিভাজন + উদ্ভিদ শারীরতত্ত্ব অধ্যায়',
    coverEmoji: '🧬',
    color: '#00B894',
    maxMembers: 10,
    weeklyStreak: 8,
    founded: '২ মাস আগে',
    language: 'bangla',
    milestones: [
      { label: 'কোষ বিজ্ঞান সম্পন্ন', achieved: true, emoji: '✅' },
      { label: 'উদ্ভিদ শারীরতত্ত্ব শেষ', achieved: true, emoji: '✅' },
      { label: 'প্রাণী শারীরতত্ত্ব শেষ', achieved: false, emoji: '🎯' },
      { label: 'মেডিকেল mock test', achieved: false, emoji: '🏆' },
    ],
    members: [
      { id: 'm12', name: 'Fatema Khatun', avatar: '👩‍🔬', class: 'class12', lastActive: '২০ মিনিট আগে', streak: 25, role: 'captain' },
      { id: 'm13', name: 'Nasir Hossain', avatar: '👨‍🔬', class: 'class12', lastActive: '৫০ মিনিট আগে', streak: 11, role: 'member' },
      { id: 'm14', name: 'Dilara Parvin', avatar: '👩‍🎓', class: 'class11', lastActive: '১.৫ ঘন্টা আগে', streak: 7, role: 'member' },
      { id: 'm15', name: 'Imran Ali', avatar: '🧑‍🔬', class: 'class12', lastActive: '৩ ঘন্টা আগে', streak: 14, role: 'member' },
    ],
    activity: [
      { id: 'c1', memberId: 'm12', memberName: 'Fatema Khatun', avatar: '👩‍🔬', type: 'join_me', content: 'সকাল ৮টায় মাইটোসিস-মিয়োসিস পড়ব একসাথে', subject: 'biology', timestamp: 'এইমাত্র', reactions: 6 },
      { id: 'c2', memberId: 'm15', memberName: 'Imran Ali', avatar: '🧑‍🔬', type: 'studied', content: 'নিউক্লিক এসিড সম্পূর্ণ নোট তৈরি করলাম', subject: 'biology', timestamp: '৩ ঘন্টা আগে', reactions: 10 },
      { id: 'c3', memberId: 'm13', memberName: 'Nasir Hossain', avatar: '👨‍🔬', type: 'stuck', content: 'ক্রেবস চক্র এখনো পুরোপুরি বুঝিনি', subject: 'biology', timestamp: '৫ ঘন্টা আগে', reactions: 4 },
      { id: 'c4', memberId: 'm14', memberName: 'Dilara Parvin', avatar: '👩‍🎓', type: 'completed', content: 'গত সপ্তাহের সব target শেষ 🎉', timestamp: 'গতকাল', reactions: 16 },
    ],
  },

  // ─── 4 ────────────────────────────────────────────────────────────────────
  {
    id: 'ssc-science-warriors',
    name: 'SSC Science Warriors',
    tagline: 'বিজ্ঞান বিভাগ — একসাথে জিতব',
    description:
      'SSC বিজ্ঞান বিভাগের চারটি বিষয় — পদার্থবিজ্ঞান, রসায়ন, জীববিজ্ঞান ও গণিত — সব একসাথে কভার করার গ্রুপ। রাতের সেশনে যারা পড়তে স্বাচ্ছন্দ্য বোধ করে তাদের জন্য। প্রতিটি বিষয়ে rotating lead — আজকে একজন physics পড়ায়, কাল আরেকজন chemistry।',
    studyApproach: [
      'Rotating subject lead — প্রতিদিন ভিন্ন কেউ পড়ায়',
      'রাতের সেশনে সপ্তাহের কঠিনতম টপিক',
      'সোমবার সাপ্তাহিক পরিকল্পনা, রবিবার review',
    ],
    rules: [
      'সব বিষয়ে সমান মনোযোগ দিতে হবে',
      'কেউ একটি বিষয় ছেড়ে দিতে পারবে না',
      'সেশন শেষে ৫ মিনিট Q&A বাধ্যতামূলক',
    ],
    tags: ['SSC', 'বিজ্ঞান বিভাগ', 'পদার্থ', 'রসায়ন', 'রাতের সেশন'],
    class: ['class9', 'class10'],
    goals: ['exam_prep', 'daily_habit'],
    subjects: ['physics', 'chemistry', 'biology', 'math'],
    timeSlot: ['morning', 'night'],
    sharedGoal: 'SSC বিজ্ঞান বিভাগ সম্পূর্ণ প্রস্তুতি',
    nextSession: 'আজ রাত ১০টায়',
    weeklyTarget: 'রসায়ন ও পদার্থ — ২টি অধ্যায় প্রতিটি',
    coverEmoji: '🔬',
    color: '#FF6B35',
    maxMembers: 14,
    weeklyStreak: 3,
    founded: '৩ সপ্তাহ আগে',
    language: 'bangla',
    milestones: [
      { label: 'পদার্থ ১ম অধ্যায়', achieved: true, emoji: '✅' },
      { label: 'রসায়ন ২য় অধ্যায়', achieved: false, emoji: '🎯' },
      { label: 'সম্মিলিত mock test', achieved: false, emoji: '🏆' },
    ],
    members: [
      { id: 'm16', name: 'Rakib Hassan', avatar: '👨‍🎓', class: 'class10', lastActive: '৩০ মিনিট আগে', streak: 10, role: 'captain' },
      { id: 'm17', name: 'Mitu Akter', avatar: '👩‍🎓', class: 'class10', lastActive: '১ ঘন্টা আগে', streak: 6, role: 'member' },
      { id: 'm18', name: 'Joy Das', avatar: '🧑‍🎓', class: 'class9', lastActive: '২ ঘন্টা আগে', streak: 3, role: 'member' },
      { id: 'm19', name: 'Amena Khatun', avatar: '👩‍💻', class: 'class10', lastActive: '৪ ঘন্টা আগে', streak: 8, role: 'member' },
      { id: 'm20', name: 'Sajid Islam', avatar: '👨‍💻', class: 'class9', lastActive: '৬ ঘন্টা আগে', streak: 1, role: 'member' },
    ],
    activity: [
      { id: 'd1', memberId: 'm16', memberName: 'Rakib Hassan', avatar: '👨‍🎓', type: 'studied', content: 'অ্যাসিড-ক্ষার বিক্রিয়া অধ্যায় সম্পন্ন', subject: 'chemistry', timestamp: '৩০ মিনিট আগে', reactions: 7 },
      { id: 'd2', memberId: 'm17', memberName: 'Mitu Akter', avatar: '👩‍🎓', type: 'stuck', content: 'আলোর প্রতিসরণে সমস্যা হচ্ছে', subject: 'physics', timestamp: '১ ঘন্টা আগে', reactions: 3 },
      { id: 'd3', memberId: 'm18', memberName: 'Joy Das', avatar: '🧑‍🎓', type: 'join_me', content: 'রাত ১০টায় একসাথে পড়ি?', timestamp: '২ ঘন্টা আগে', reactions: 5 },
    ],
  },

  // ─── 5 ────────────────────────────────────────────────────────────────────
  {
    id: 'hsc-english-masters',
    name: 'HSC English Masters',
    tagline: 'ইংরেজি ভয় দূর করি একসাথে',
    description:
      'HSC ইংরেজিতে যারা কমজোরি তাদের জন্য — writing, grammar, comprehension সব একসাথে। Essay, paragraph, letter writing প্র্যাকটিস করা হয় প্রতি সেশনে। এখানে ইংরেজিতে কথা বলতে ইতস্তত করার কিছু নেই — সবাই শিখছে, সবাই একসাথে।',
    studyApproach: [
      'প্রতিদিন ১টি essay বা paragraph লেখা + feedback',
      'Grammar MCQ দ্রুত সমাধান দলীয়ভাবে',
      'Reading comprehension সপ্তাহে ২দিন',
    ],
    rules: [
      'লেখার ভুল ধরিয়ে দেওয়া — সহানুভূতির সাথে',
      'কমপক্ষে সপ্তাহে ৩দিন সক্রিয় থাকতে হবে',
      'ইংরেজিতে কথা বলার চেষ্টা করা উৎসাহিত',
    ],
    tags: ['HSC', 'ইংরেজি', 'Writing', 'Grammar', 'বিকালের সেশন'],
    class: ['class11', 'class12'],
    goals: ['weak_subject', 'exam_prep'],
    subjects: ['english', 'bangla'],
    timeSlot: ['afternoon', 'evening'],
    sharedGoal: 'HSC ইংরেজি ১ম ও ২য় পত্র — Writing + Grammar',
    nextSession: 'আগামীকাল বিকাল ৪টায়',
    weeklyTarget: 'Essay writing + ৫০টি grammar MCQ',
    coverEmoji: '📚',
    color: '#0984E3',
    maxMembers: 12,
    weeklyStreak: 5,
    founded: '৫ সপ্তাহ আগে',
    language: 'both',
    milestones: [
      { label: 'Grammar basics সম্পন্ন', achieved: true, emoji: '✅' },
      { label: '১০টি Essay practice', achieved: true, emoji: '✅' },
      { label: 'Comprehension mastery', achieved: false, emoji: '🎯' },
    ],
    members: [
      { id: 'm21', name: 'Tania Akter', avatar: '👩‍📚', class: 'class12', lastActive: '৪৫ মিনিট আগে', streak: 13, role: 'captain' },
      { id: 'm22', name: 'Sabbir Rahman', avatar: '👨‍📚', class: 'class11', lastActive: '২ ঘন্টা আগে', streak: 7, role: 'member' },
      { id: 'm23', name: 'Anika Sultana', avatar: '👩‍🎓', class: 'class12', lastActive: '৩ ঘন্টা আগে', streak: 19, role: 'member' },
    ],
    activity: [
      { id: 'e1', memberId: 'm21', memberName: 'Tania Akter', avatar: '👩‍📚', type: 'completed', content: 'Paragraph writing ৫টি শেষ করলাম', subject: 'english', timestamp: '৪৫ মিনিট আগে', reactions: 8 },
      { id: 'e2', memberId: 'm22', memberName: 'Sabbir Rahman', avatar: '👨‍📚', type: 'stuck', content: 'Conditional sentences বুঝছি না', subject: 'english', timestamp: '২ ঘন্টা আগে', reactions: 2 },
      { id: 'e3', memberId: 'm23', memberName: 'Anika Sultana', avatar: '👩‍🎓', type: 'join_me', content: 'Grammar session — আজ বিকাল ৪টায়', timestamp: '৩ ঘন্টা আগে', reactions: 6 },
    ],
  },

  // ─── 6 ────────────────────────────────────────────────────────────────────
  {
    id: 'class9-allrounder',
    name: 'Class 9 All-Rounders',
    tagline: 'নবম শ্রেণীর শুরু থেকে শক্ত ভিত্তি',
    description:
      'নবম শ্রেণীতে নতুন এসেছ? অনেক বিষয় একসাথে সামলানো কঠিন লাগছে? এই গ্রুপ তোমার জন্য — সব বিষয় কভার করব নিয়মিত। প্রতিদিনের পড়াশোনার অভ্যাস তৈরি করাই প্রধান লক্ষ্য। সিনিয়র যারা আছে তারাও সাহায্য করে।',
    studyApproach: [
      'প্রতিদিন ২ ঘন্টা — বিষয় rotate করে',
      'সাপ্তাহিক পরিকল্পনা সোমবার ঠিক হয়',
      'প্রতিটি অধ্যায় শেষে quiz নিজেরাই তৈরি করি',
    ],
    rules: [
      'নতুনরা সব সময় স্বাগত',
      'অলসতা ধরা পড়লে friendly nudge পাবে',
      'সপ্তাহে কমপক্ষে ৫ দিন চেক-ইন করতে হবে',
    ],
    tags: ['ক্লাস ৯', 'সব বিষয়', 'নিয়মিত অভ্যাস', 'শুরু থেকে', 'বিকালের সেশন'],
    class: ['class9'],
    goals: ['daily_habit', 'weak_subject'],
    subjects: ['math', 'english', 'bangla', 'ict'],
    timeSlot: ['afternoon', 'evening'],
    sharedGoal: 'নবম শ্রেণীর সব বিষয় — নিয়মিত পড়ার অভ্যাস তৈরি',
    nextSession: 'আজ বিকাল ৫:৩০টায়',
    weeklyTarget: 'প্রতিদিন ২ ঘন্টা — সব বিষয় কভার',
    coverEmoji: '🌟',
    color: '#F39C12',
    maxMembers: 16,
    weeklyStreak: 2,
    founded: '২ সপ্তাহ আগে',
    language: 'bangla',
    milestones: [
      { label: '১ম সপ্তাহ সম্পন্ন', achieved: true, emoji: '✅' },
      { label: 'প্রথম quiz শেষ', achieved: false, emoji: '🎯' },
    ],
    members: [
      { id: 'm24', name: 'Mahdi Islam', avatar: '👦', class: 'class9', lastActive: '১ ঘন্টা আগে', streak: 4, role: 'captain' },
      { id: 'm25', name: 'Rupa Begum', avatar: '👧', class: 'class9', lastActive: '২ ঘন্টা আগে', streak: 6, role: 'member' },
      { id: 'm26', name: 'Tomal Ahmed', avatar: '🧒', class: 'class9', lastActive: '৩ ঘন্টা আগে', streak: 2, role: 'member' },
    ],
    activity: [
      { id: 'f1', memberId: 'm24', memberName: 'Mahdi Islam', avatar: '👦', type: 'studied', content: 'আজকে গণিত আর ইংরেজি দুটোই পড়লাম', timestamp: '১ ঘন্টা আগে', reactions: 5 },
      { id: 'f2', memberId: 'm25', memberName: 'Rupa Begum', avatar: '👧', type: 'join_me', content: 'বিকাল ৫:৩০টায় একসাথে পড়ি?', timestamp: '২ ঘন্টা আগে', reactions: 3 },
    ],
  },

  // ─── 7 ────────────────────────────────────────────────────────────────────
  {
    id: 'hsc-chemistry-crushers',
    name: 'HSC Chemistry Crushers',
    tagline: 'রসায়ন বোঝো — মুখস্থ নয়',
    description:
      'HSC রসায়নের জৈব রসায়ন, তড়িৎ রসায়ন ও বিক্রিয়ার কৌশল — এই অধ্যায়গুলো অনেকের কাছে সবচেয়ে কঠিন। আমরা প্রতিটি বিক্রিয়া কেন হয় সেটা বুঝে পড়ি। যে equation মুখস্থ হয় না, সেটার পেছনের logic বের করি একসাথে।',
    studyApproach: [
      'প্রতি সেশনে ১টি mechanism বিস্তারিত বিশ্লেষণ',
      'রঙিন diagram + নোট শেয়ার করা হয়',
      'প্রতি শুক্রবার জৈব রসায়ন চ্যালেঞ্জ',
    ],
    rules: [
      'শুধু মুখস্থ নয় — কারণ বুঝতে হবে',
      'নিজের নোট সার্কেলে শেয়ার করা উৎসাহিত',
      'ভুল হলে ঠিক করে দাও — কিন্তু সম্মানের সাথে',
    ],
    tags: ['HSC', 'রসায়ন', 'জৈব রসায়ন', 'মেডিকেল', 'ইঞ্জিনিয়ারিং'],
    class: ['class11', 'class12'],
    goals: ['exam_prep', 'weak_subject', 'admission_prep'],
    subjects: ['chemistry', 'biology', 'physics'],
    timeSlot: ['afternoon', 'evening'],
    sharedGoal: 'HSC রসায়ন ১ম ও ২য় পত্র — জৈব রসায়ন ও তড়িৎ রসায়ন',
    nextSession: 'আজ সন্ধ্যা ৭টায়',
    weeklyTarget: 'জৈব রসায়ন ৩টি অধ্যায় + সব বিক্রিয়া',
    coverEmoji: '⚗️',
    color: '#6C5CE7',
    maxMembers: 12,
    weeklyStreak: 7,
    founded: '৭ সপ্তাহ আগে',
    language: 'bangla',
    milestones: [
      { label: 'অজৈব রসায়ন শেষ', achieved: true, emoji: '✅' },
      { label: 'তড়িৎ রসায়ন সম্পন্ন', achieved: true, emoji: '✅' },
      { label: 'জৈব রসায়ন শেষ', achieved: false, emoji: '🎯' },
      { label: 'বোর্ড প্রশ্ন সমাধান', achieved: false, emoji: '🏆' },
    ],
    members: [
      { id: 'n1', name: 'Sadia Islam', avatar: '👩‍🔬', class: 'class12', lastActive: 'এইমাত্র', streak: 17, role: 'captain' },
      { id: 'n2', name: 'Farhan Hossain', avatar: '👨‍🔬', class: 'class12', lastActive: '২০ মিনিট আগে', streak: 9, role: 'member' },
      { id: 'n3', name: 'Nusrat Jahan', avatar: '👩‍🎓', class: 'class11', lastActive: '৫০ মিনিট আগে', streak: 12, role: 'member' },
      { id: 'n4', name: 'Kamrul Islam', avatar: '🧑‍🔬', class: 'class12', lastActive: '২ ঘন্টা আগে', streak: 5, role: 'member' },
      { id: 'n5', name: 'Asma Khatun', avatar: '👩‍💻', class: 'class11', lastActive: '৩ ঘন্টা আগে', streak: 8, role: 'member' },
    ],
    activity: [
      { id: 'g1', memberId: 'n1', memberName: 'Sadia Islam', avatar: '👩‍🔬', type: 'join_me', content: 'Aldehyde & Ketone নিয়ে আলোচনা করব — এখনই আসো', subject: 'chemistry', timestamp: '৫ মিনিট আগে', reactions: 9 },
      { id: 'g2', memberId: 'n3', memberName: 'Nusrat Jahan', avatar: '👩‍🎓', type: 'completed', content: 'Electrochemistry-র সব সমীকরণ নোট করা শেষ ✅', subject: 'chemistry', timestamp: '১ ঘন্টা আগে', reactions: 11 },
      { id: 'g3', memberId: 'n4', memberName: 'Kamrul Islam', avatar: '🧑‍🔬', type: 'stuck', content: 'SN1 vs SN2 reaction mechanism পার্থক্য বুঝছি না', subject: 'chemistry', timestamp: '৩ ঘন্টা আগে', reactions: 5 },
      { id: 'g4', memberId: 'n2', memberName: 'Farhan Hossain', avatar: '👨‍🔬', type: 'studied', content: 'আজকে ৪ ঘন্টা জৈব রসায়ন — তৃতীয় অধ্যায় শেষ', subject: 'chemistry', timestamp: '৫ ঘন্টা আগে', reactions: 13 },
    ],
  },

  // ─── 8 ────────────────────────────────────────────────────────────────────
  {
    id: 'ssc-english-builders',
    name: 'SSC English Builders',
    tagline: 'ইংরেজিতে ভালো করা যায় — আমরাই প্রমাণ',
    description:
      'SSC ইংরেজিতে যারা পিছিয়ে আছ তাদের জন্য একটি সহযোগিতামূলক গ্রুপ। Grammar নিয়মিত চর্চা, paragraph ও letter লেখার অভ্যাস, আর reading comprehension একসাথে সমাধান — সবকিছু ধাপে ধাপে। ইংরেজি ভয়ের বিষয় নয়, একটু practice-এ সবাই পারে।',
    studyApproach: [
      'Grammar → Writing → Reading — এই ক্রমে প্রতিটি সেশন',
      'প্রতিদিন ১০টি vocabulary নতুন শেখা',
      'বাস্তব উদাহরণ দিয়ে Grammar শেখানো',
    ],
    rules: [
      'বাংলায় বুঝিয়ে ইংরেজি শেখানো — কেউ হারিয়ে যাবে না',
      'প্রতিদিন অন্তত ১টি sentence লেখার চেষ্টা',
      'ভুল grammar নিয়ে হাসাহাসি বন্ধ',
    ],
    tags: ['SSC', 'ইংরেজি', 'Grammar', 'Writing', 'দুর্বল বিষয়'],
    class: ['class9', 'class10'],
    goals: ['weak_subject', 'exam_prep', 'daily_habit'],
    subjects: ['english', 'bangla'],
    timeSlot: ['afternoon', 'evening'],
    sharedGoal: 'SSC ইংরেজি ১ম ও ২য় পত্র — Grammar + Writing দক্ষতা',
    nextSession: 'আজ বিকাল ৪টায়',
    weeklyTarget: 'Tense + Voice + Narration সম্পন্ন',
    coverEmoji: '✍️',
    color: '#00CEC9',
    maxMembers: 14,
    weeklyStreak: 3,
    founded: '৩ সপ্তাহ আগে',
    language: 'both',
    milestones: [
      { label: 'Parts of Speech শেষ', achieved: true, emoji: '✅' },
      { label: 'Tense mastery', achieved: false, emoji: '🎯' },
      { label: 'SSC mock test', achieved: false, emoji: '🏆' },
    ],
    members: [
      { id: 'p1', name: 'Lipi Akter', avatar: '👩‍📚', class: 'class10', lastActive: '৩০ মিনিট আগে', streak: 8, role: 'captain' },
      { id: 'p2', name: 'Sujon Mia', avatar: '👨‍📚', class: 'class10', lastActive: '১ ঘন্টা আগে', streak: 5, role: 'member' },
      { id: 'p3', name: 'Meher Nisa', avatar: '👩‍🎓', class: 'class9', lastActive: '২ ঘন্টা আগে', streak: 3, role: 'member' },
      { id: 'p4', name: 'Rubel Hasan', avatar: '🧑‍📚', class: 'class10', lastActive: '৪ ঘন্টা আগে', streak: 6, role: 'member' },
    ],
    activity: [
      { id: 'h1', memberId: 'p1', memberName: 'Lipi Akter', avatar: '👩‍📚', type: 'join_me', content: 'Passive Voice practice করব বিকালে — সবাই আসো', subject: 'english', timestamp: '৩০ মিনিট আগে', reactions: 7 },
      { id: 'h2', memberId: 'p3', memberName: 'Meher Nisa', avatar: '👩‍🎓', type: 'stuck', content: 'Reported speech এ confuse হচ্ছি', subject: 'english', timestamp: '১ ঘন্টা আগে', reactions: 4 },
      { id: 'h3', memberId: 'p2', memberName: 'Sujon Mia', avatar: '👨‍📚', type: 'studied', content: 'আজ ২০টি sentence লিখলাম — grammar check করে নিলাম', subject: 'english', timestamp: '৩ ঘন্টা আগে', reactions: 6 },
    ],
  },

  // ─── 9 ────────────────────────────────────────────────────────────────────
  {
    id: 'hsc-math-olympians',
    name: 'HSC Math Olympians',
    tagline: 'গণিতে দুর্দান্ত হতে চাও? এখানে আসো',
    description:
      'HSC গণিতে যারা সত্যিকার দক্ষতা অর্জন করতে চাও — শুধু পাস নয়, A+ — তাদের জন্য। ক্যালকুলাস, ভেক্টর, জটিল সংখ্যা, ম্যাট্রিক্স — প্রতিটি টপিকে গভীরে যাওয়া হয়। সকালের তাজা মাথায় সবচেয়ে কঠিন সমস্যা সমাধান করা হয়।',
    studyApproach: [
      'প্রতি সেশনে ১টি কঠিন theorem proof করা',
      'Board question এর বাইরে extra problem সমাধান',
      'প্রতিযোগিতামূলক — দ্রুততম সমাধানকারী স্বীকৃতি পায়',
    ],
    rules: [
      'সত্যিকারের পরিশ্রম ছাড়া এই গ্রুপে থাকা যাবে না',
      'প্রতিদিন অন্তত ৩টি সমস্যা সমাধান বাধ্যতামূলক',
      'সমাধান শেয়ার করতে হবে — শুধু answer নয়, পুরো process',
    ],
    tags: ['HSC', 'গণিত', 'ক্যালকুলাস', 'A+', 'সকালের সেশন', 'advanced'],
    class: ['class11', 'class12'],
    goals: ['exam_prep', 'admission_prep'],
    subjects: ['math', 'physics'],
    timeSlot: ['morning', 'afternoon'],
    sharedGoal: 'HSC গণিতে A+ এবং ইঞ্জিনিয়ারিং ভর্তি প্রস্তুতি',
    nextSession: 'আগামীকাল সকাল ৭টায়',
    weeklyTarget: 'ক্যালকুলাস ৩টি theorem + ২০টি সমস্যা',
    coverEmoji: '🧮',
    color: '#2D3436',
    maxMembers: 10,
    weeklyStreak: 10,
    founded: '১০ সপ্তাহ আগে',
    language: 'both',
    milestones: [
      { label: 'Differentiation mastery', achieved: true, emoji: '✅' },
      { label: 'Integration সম্পন্ন', achieved: true, emoji: '✅' },
      { label: 'Vector + Complex Numbers', achieved: true, emoji: '✅' },
      { label: 'Matrices সম্পন্ন', achieved: false, emoji: '🎯' },
      { label: 'BUET প্রস্তুতি mock', achieved: false, emoji: '🏆' },
    ],
    members: [
      { id: 'q1', name: 'Anisur Rahman', avatar: '👨‍💻', class: 'class12', lastActive: '১ ঘন্টা আগে', streak: 35, role: 'captain' },
      { id: 'q2', name: 'Sinthia Hasan', avatar: '👩‍💻', class: 'class12', lastActive: '২ ঘন্টা আগে', streak: 28, role: 'member' },
      { id: 'q3', name: 'Rayhan Ali', avatar: '🧑‍🎓', class: 'class11', lastActive: '৩ ঘন্টা আগে', streak: 20, role: 'member' },
      { id: 'q4', name: 'Tamanna Islam', avatar: '👩‍🎓', class: 'class12', lastActive: '৫ ঘন্টা আগে', streak: 22, role: 'member' },
    ],
    activity: [
      { id: 'i1', memberId: 'q1', memberName: 'Anisur Rahman', avatar: '👨‍💻', type: 'completed', content: 'Matrix determinant এবং inverse সব problem শেষ 💪', subject: 'math', timestamp: '১ ঘন্টা আগে', reactions: 18 },
      { id: 'i2', memberId: 'q3', memberName: 'Rayhan Ali', avatar: '🧑‍🎓', type: 'stuck', content: 'Differential equation-এর particular solution বের করতে পারছি না', subject: 'math', timestamp: '৩ ঘন্টা আগে', reactions: 6 },
      { id: 'i3', memberId: 'q2', memberName: 'Sinthia Hasan', avatar: '👩‍💻', type: 'join_me', content: 'সকাল ৭টায় ক্যালকুলাস session — hardcore mode চালু', subject: 'math', timestamp: '৫ ঘন্টা আগে', reactions: 12 },
    ],
  },

  // ─── 10 ───────────────────────────────────────────────────────────────────
  {
    id: 'ssc-final-push',
    name: 'SSC Final Push — Class 10 Sprint',
    tagline: 'পরীক্ষা আসছে — শেষ মাসের সর্বোচ্চ প্রস্তুতি',
    description:
      'SSC পরীক্ষার শেষ ৪ সপ্তাহের জন্য তৈরি একটি intensive sprint group। শুধু Class 10 শিক্ষার্থীদের জন্য। প্রতিদিন ৪-৫ ঘন্টার focused study, revision plan, এবং subject-wise weak point চিহ্নিত করে সেগুলো শেষ সময়ে ঠিক করা।',
    studyApproach: [
      'প্রতিদিন ২টি বিষয় revision',
      'শেষ ৫ বছরের board question সমাধান',
      'দিনের শেষে self-assessment — কতটুকু শেখা হলো',
    ],
    rules: [
      'এটি শুধু Class 10 এর জন্য — অন্য class নয়',
      'পরীক্ষার আগ পর্যন্ত প্রতিদিন check-in বাধ্যতামূলক',
      'Phone বাদ দিয়ে সেশনে মনোযোগ',
    ],
    tags: ['SSC', 'ক্লাস ১০', 'Final Exam', 'Sprint', 'Intensive', 'রাতের সেশন'],
    class: ['class10'],
    goals: ['exam_prep'],
    subjects: ['math', 'physics', 'chemistry', 'biology', 'english', 'bangla'],
    timeSlot: ['morning', 'night'],
    sharedGoal: 'SSC পরীক্ষায় A+ পাওয়া — শেষ ৪ সপ্তাহের সর্বোচ্চ প্রস্তুতি',
    nextSession: 'আজ রাত ৯:৩০টায়',
    weeklyTarget: 'সব বিষয়ে revision শেষ + ৩টি mock test',
    coverEmoji: '🚀',
    color: '#D63031',
    maxMembers: 10,
    weeklyStreak: 4,
    founded: '৪ সপ্তাহ আগে',
    language: 'bangla',
    milestones: [
      { label: 'সপ্তাহ ১ revision শেষ', achieved: true, emoji: '✅' },
      { label: 'সপ্তাহ ২ revision শেষ', achieved: true, emoji: '✅' },
      { label: 'সপ্তাহ ৩ revision', achieved: false, emoji: '🎯' },
      { label: 'SSC পরীক্ষা দিন', achieved: false, emoji: '🏆' },
    ],
    members: [
      { id: 'r1', name: 'Habib Ullah', avatar: '👨‍🎓', class: 'class10', lastActive: '৩০ মিনিট আগে', streak: 16, role: 'captain' },
      { id: 'r2', name: 'Roksana Begum', avatar: '👩‍🎓', class: 'class10', lastActive: '১ ঘন্টা আগে', streak: 14, role: 'member' },
      { id: 'r3', name: 'Zahir Islam', avatar: '🧑‍🎓', class: 'class10', lastActive: '২ ঘন্টা আগে', streak: 11, role: 'member' },
      { id: 'r4', name: 'Poly Akter', avatar: '👩‍💻', class: 'class10', lastActive: '৩ ঘন্টা আগে', streak: 9, role: 'member' },
      { id: 'r5', name: 'Nadim Ahmed', avatar: '👨‍💻', class: 'class10', lastActive: 'এইমাত্র', streak: 20, role: 'member' },
    ],
    activity: [
      { id: 'j1', memberId: 'r5', memberName: 'Nadim Ahmed', avatar: '👨‍💻', type: 'join_me', content: 'রাত ৯:৩০ এ পদার্থবিজ্ঞান revision — সবাই আসো!', subject: 'physics', timestamp: '১০ মিনিট আগে', reactions: 9 },
      { id: 'j2', memberId: 'r1', memberName: 'Habib Ullah', avatar: '👨‍🎓', type: 'completed', content: 'গণিত এবং রসায়ন দুটো revision শেষ আজকে ✅', timestamp: '২ ঘন্টা আগে', reactions: 14 },
      { id: 'j3', memberId: 'r3', memberName: 'Zahir Islam', avatar: '🧑‍🎓', type: 'stuck', content: 'জীববিজ্ঞানের রেচন অধ্যায় গুলিয়ে ফেলছি', subject: 'biology', timestamp: '৩ ঘন্টা আগে', reactions: 3 },
      { id: 'j4', memberId: 'r2', memberName: 'Roksana Begum', avatar: '👩‍🎓', type: 'studied', content: 'বাংলা ২য় পত্র সব ব্যাকরণ chapter revision', subject: 'bangla', timestamp: '৫ ঘন্টা আগে', reactions: 8 },
    ],
  },

  // ─── 11 ───────────────────────────────────────────────────────────────────
  {
    id: 'hsc-ict-masters',
    name: 'HSC ICT Masters',
    tagline: 'তথ্য প্রযুক্তি — theory + practical একসাথে',
    description:
      'HSC ICT-তে অনেকেই theory পড়ে কিন্তু practical অংশ — programming, database, network — এগুলো দুর্বল থাকে। এই গ্রুপে দুটোই কভার করা হয়। Algorithm, C programming, HTML/CSS এর হাতে-কলমে অভ্যাস।',
    studyApproach: [
      'Theory পড়া → তারপর practical করা একই session-এ',
      'সাপ্তাহিক mini coding challenge',
      'ICT board question গুলো pattern বিশ্লেষণ',
    ],
    rules: [
      'Laptop বা computer হলে সাথে রাখতে হবে',
      'Code লিখে দেখানো — শুধু মুখে বলা নয়',
      'অন্যের code review করার চেষ্টা করো',
    ],
    tags: ['HSC', 'ICT', 'Programming', 'Database', 'Networking', 'সন্ধ্যার সেশন'],
    class: ['class11', 'class12'],
    goals: ['exam_prep', 'weak_subject'],
    subjects: ['ict', 'math'],
    timeSlot: ['evening', 'night'],
    sharedGoal: 'HSC ICT তত্ত্ব + ব্যবহারিক সম্পূর্ণ আয়ত্ত করা',
    nextSession: 'পরশু সন্ধ্যা ৬:৩০টায়',
    weeklyTarget: 'C programming অধ্যায় + Database normalization',
    coverEmoji: '💻',
    color: '#0652DD',
    maxMembers: 12,
    weeklyStreak: 5,
    founded: '৫ সপ্তাহ আগে',
    language: 'both',
    milestones: [
      { label: 'Number system শেষ', achieved: true, emoji: '✅' },
      { label: 'Algorithm & Flowchart', achieved: true, emoji: '✅' },
      { label: 'C programming সম্পন্ন', achieved: false, emoji: '🎯' },
      { label: 'Database অধ্যায়', achieved: false, emoji: '🎯' },
    ],
    members: [
      { id: 's1', name: 'Naim Hasan', avatar: '👨‍💻', class: 'class12', lastActive: '৪৫ মিনিট আগে', streak: 14, role: 'captain' },
      { id: 's2', name: 'Faria Akter', avatar: '👩‍💻', class: 'class11', lastActive: '১.৫ ঘন্টা আগে', streak: 9, role: 'member' },
      { id: 's3', name: 'Mahfuz Islam', avatar: '🧑‍💻', class: 'class12', lastActive: '৩ ঘন্টা আগে', streak: 7, role: 'member' },
      { id: 's4', name: 'Kakoli Das', avatar: '👩‍🎓', class: 'class11', lastActive: '৫ ঘন্টা আগে', streak: 4, role: 'member' },
    ],
    activity: [
      { id: 'k1', memberId: 's1', memberName: 'Naim Hasan', avatar: '👨‍💻', type: 'completed', content: 'C-তে bubble sort algorithm লিখে দেখালাম ✅', subject: 'ict', timestamp: '৪৫ মিনিট আগে', reactions: 10 },
      { id: 'k2', memberId: 's3', memberName: 'Mahfuz Islam', avatar: '🧑‍💻', type: 'stuck', content: 'Relational database-এ foreign key বুঝছি না', subject: 'ict', timestamp: '৩ ঘন্টা আগে', reactions: 4 },
      { id: 'k3', memberId: 's2', memberName: 'Faria Akter', avatar: '👩‍💻', type: 'studied', content: 'Network topology সব diagram নোট করা শেষ', subject: 'ict', timestamp: '৪ ঘন্টা আগে', reactions: 7 },
    ],
  },

  // ─── 12 ───────────────────────────────────────────────────────────────────
  {
    id: 'morning-warriors',
    name: 'Morning Warriors — সকালের পড়ুয়া দল',
    tagline: 'ভোরে উঠে পড়লে দিন হয় সোনার',
    description:
      'সব class, সব বিষয়ের শিক্ষার্থী — যাদের একটাই মিল: সকালে পড়ার অভ্যাস আছে বা তৈরি করতে চায়। ভোর ৬-৮টার মধ্যে যারা পড়াশোনা শুরু করে তারা অনেক বেশি focus করতে পারে। এই গ্রুপ সেই অভ্যাস ধরে রাখার জন্য।',
    studyApproach: [
      'সকাল ৬:৩০টায় check-in — সবাই কে পড়তে বসেছ?',
      '৯০ মিনিট focused study, তারপর শেয়ারিং',
      'কেউ না উঠলে বাকিরা nudge পাঠায়',
    ],
    rules: [
      'সকাল ৭টার আগে check-in করলে streak মেলে',
      'Distraction নেই — phone silent রাখতে হবে',
      'সকালে কী পড়লে সেটা feed-এ share করতে হবে',
    ],
    tags: ['সব ক্লাস', 'সকাল', 'অভ্যাস', 'Accountability', 'Cross-class'],
    class: ['class9', 'class10', 'class11', 'class12'],
    goals: ['daily_habit', 'exam_prep'],
    subjects: ['math', 'physics', 'chemistry', 'biology', 'english', 'bangla', 'ict'],
    timeSlot: ['morning'],
    sharedGoal: 'প্রতিদিন সকালে পড়ার অভ্যাস তৈরি ও ধরে রাখা',
    nextSession: 'আগামীকাল সকাল ৬:৩০টায়',
    weeklyTarget: 'সপ্তাহে ৬ দিন সকাল ৭টার আগে check-in',
    coverEmoji: '🌅',
    color: '#E17055',
    maxMembers: 20,
    weeklyStreak: 9,
    founded: '৯ সপ্তাহ আগে',
    language: 'bangla',
    milestones: [
      { label: '১ম মাস সম্পন্ন', achieved: true, emoji: '✅' },
      { label: '৫০ দিনের streak', achieved: true, emoji: '✅' },
      { label: '৩ মাসের streak', achieved: false, emoji: '🎯' },
    ],
    members: [
      { id: 't1', name: 'Taslima Begum', avatar: '👩‍🌅', class: 'class12', lastActive: 'এইমাত্র', streak: 42, role: 'captain' },
      { id: 't2', name: 'Ismail Hossain', avatar: '👨‍🌅', class: 'class10', lastActive: '৩০ মিনিট আগে', streak: 35, role: 'member' },
      { id: 't3', name: 'Nargis Akter', avatar: '👩‍🎓', class: 'class11', lastActive: '১ ঘন্টা আগে', streak: 28, role: 'member' },
      { id: 't4', name: 'Raju Ahmed', avatar: '👨‍🎓', class: 'class9', lastActive: '২ ঘন্টা আগে', streak: 15, role: 'member' },
      { id: 't5', name: 'Sultana Razia', avatar: '👩‍💻', class: 'class12', lastActive: '৩ ঘন্টা আগে', streak: 30, role: 'member' },
    ],
    activity: [
      { id: 'l1', memberId: 't1', memberName: 'Taslima Begum', avatar: '👩‍🌅', type: 'studied', content: 'সকাল ৬:২০-এ check-in ✅ আজ পদার্থবিজ্ঞান', subject: 'physics', timestamp: '৫ মিনিট আগে', reactions: 11 },
      { id: 'l2', memberId: 't2', memberName: 'Ismail Hossain', avatar: '👨‍🌅', type: 'studied', content: 'সকাল ৬:৪৫ — গণিত শেষ করব আজ!', subject: 'math', timestamp: '৩০ মিনিট আগে', reactions: 8 },
      { id: 'l3', memberId: 't4', memberName: 'Raju Ahmed', avatar: '👨‍🎓', type: 'join_me', content: 'আজ কে কে উঠেছ? চেক-ইন করো সবাই!', timestamp: '১ ঘন্টা আগে', reactions: 13 },
      { id: 'l4', memberId: 't3', memberName: 'Nargis Akter', avatar: '👩‍🎓', type: 'completed', content: '৭ দিনে ৭ দিনই check-in — streak চালু আছে! 🔥', timestamp: 'গতকাল', reactions: 19 },
    ],
  },

  // ─── 13 ───────────────────────────────────────────────────────────────────
  {
    id: 'ssc-bangla-writers',
    name: 'SSC Bangla Excellence',
    tagline: 'বাংলায় ভালো লিখতে শিখি একসাথে',
    description:
      'SSC বাংলা ১ম ও ২য় পত্রের জন্য — রচনা, সারাংশ, ভাব-সম্প্রসারণ এবং ব্যাকরণ। অনেকেই বাংলাকে সহজ মনে করে অবহেলা করে, তারপর পরীক্ষায় গিয়ে ভুল করে। এই গ্রুপে বাংলা সিরিয়াসলি নেওয়া হয়।',
    studyApproach: [
      'প্রতি সেশনে ১টি রচনা বা সারাংশ লেখা',
      'ব্যাকরণ — সন্ধি, সমাস, কারক সব cover করা',
      'একে অপরের লেখা review করা',
    ],
    rules: [
      'বাংলা বানান সঠিক রাখতে হবে',
      'নিজের লেখা share করতে হবে — shy হলে চলবে না',
      'সাহিত্যের কবিতা ও গল্প — অর্থ বুঝে পড়া',
    ],
    tags: ['SSC', 'বাংলা', 'রচনা', 'ব্যাকরণ', 'সাহিত্য', 'বিকালের সেশন'],
    class: ['class9', 'class10'],
    goals: ['exam_prep', 'weak_subject'],
    subjects: ['bangla', 'english'],
    timeSlot: ['afternoon', 'evening'],
    sharedGoal: 'SSC বাংলা ১ম ও ২য় পত্রে A+ পাওয়া',
    nextSession: 'আজ বিকাল ৩:৩০টায়',
    weeklyTarget: 'ৎ রচনা + সন্ধি বিচ্ছেদ সব rule',
    coverEmoji: '📝',
    color: '#00B894',
    maxMembers: 14,
    weeklyStreak: 5,
    founded: '৫ সপ্তাহ আগে',
    language: 'bangla',
    milestones: [
      { label: 'ব্যাকরণ ১ম অধ্যায়', achieved: true, emoji: '✅' },
      { label: 'কবিতা সব cover', achieved: true, emoji: '✅' },
      { label: 'রচনা ২০টি practice', achieved: false, emoji: '🎯' },
    ],
    members: [
      { id: 'u1', name: 'Moriom Khatun', avatar: '👩‍📖', class: 'class10', lastActive: '২০ মিনিট আগে', streak: 12, role: 'captain' },
      { id: 'u2', name: 'Biplab Roy', avatar: '👨‍📖', class: 'class10', lastActive: '১ ঘন্টা আগে', streak: 7, role: 'member' },
      { id: 'u3', name: 'Shahanara Begum', avatar: '👩‍🎓', class: 'class9', lastActive: '২ ঘন্টা আগে', streak: 5, role: 'member' },
      { id: 'u4', name: 'Miraj Islam', avatar: '🧑‍📖', class: 'class10', lastActive: '৪ ঘন্টা আগে', streak: 9, role: 'member' },
    ],
    activity: [
      { id: 'm1', memberId: 'u1', memberName: 'Moriom Khatun', avatar: '👩‍📖', type: 'join_me', content: 'বিকাল ৩:৩০-এ রচনা writing session — সবাই আসো', subject: 'bangla', timestamp: '২০ মিনিট আগে', reactions: 6 },
      { id: 'm2', memberId: 'u3', memberName: 'Shahanara Begum', avatar: '👩‍🎓', type: 'stuck', content: 'বিসর্গ সন্ধি বুঝছি না একদম', subject: 'bangla', timestamp: '২ ঘন্টা আগে', reactions: 3 },
      { id: 'm3', memberId: 'u2', memberName: 'Biplab Roy', avatar: '👨‍📖', type: 'completed', content: '"আমার পথ" প্রবন্ধের সারাংশ লিখে শেষ করলাম', subject: 'bangla', timestamp: '৩ ঘন্টা আগে', reactions: 8 },
    ],
  },

  // ─── 14 ───────────────────────────────────────────────────────────────────
  {
    id: 'night-owls-admission',
    name: 'Night Owls — Admission Squad',
    tagline: 'রাতে জেগে স্বপ্ন পূরণ করি একসাথে',
    description:
      'HSC শেষে মেডিকেল, BUET বা পাবলিক বিশ্ববিদ্যালয়ের ভর্তি পরীক্ষার প্রস্তুতির জন্য রাতের গ্রুপ। যারা দিনে ব্যস্ত থাকে কিন্তু রাত ১০টার পর মনোযোগ দিতে পারে তাদের জন্য। সিলেবাস বিশাল — কিন্তু একসাথে পড়লে কোনোটাই অসম্ভব নয়।',
    studyApproach: [
      'রাত ১০টা থেকে ১২টা — সবচেয়ে productive সময়',
      'Medical, BUET, DU-তে কী আসে সেটা analyze করা',
      'প্রতিদিন ১টি subject intensive — rotate করে',
    ],
    rules: [
      'শুধু ক্লাস ১২ এবং সদ্য HSC শেষ করা শিক্ষার্থীদের জন্য',
      'রাত ১০টায় online থাকতে হবে',
      'ঘুম না এলে পড়তে বস — ঘুম পরে হবে',
    ],
    tags: ['ভর্তি পরীক্ষা', 'মেডিকেল', 'BUET', 'রাতের সেশন', 'HSC পরবর্তী'],
    class: ['class12'],
    goals: ['admission_prep', 'exam_prep'],
    subjects: ['physics', 'chemistry', 'biology', 'math'],
    timeSlot: ['night'],
    sharedGoal: 'মেডিকেল / BUET / পাবলিক বিশ্ববিদ্যালয় ভর্তি পরীক্ষায় সফল হওয়া',
    nextSession: 'আজ রাত ১০টায়',
    weeklyTarget: 'Physics + Chemistry — full revision + ১০০ MCQ practice',
    coverEmoji: '🌙',
    color: '#2C3E50',
    maxMembers: 12,
    weeklyStreak: 11,
    founded: '১১ সপ্তাহ আগে',
    language: 'bangla',
    milestones: [
      { label: 'Physics ১ম revision', achieved: true, emoji: '✅' },
      { label: 'Chemistry ১ম revision', achieved: true, emoji: '✅' },
      { label: 'Biology ১ম revision', achieved: true, emoji: '✅' },
      { label: 'Full mock test ১', achieved: true, emoji: '✅' },
      { label: 'Full mock test ২', achieved: false, emoji: '🎯' },
      { label: 'ভর্তি পরীক্ষা দিন', achieved: false, emoji: '🏆' },
    ],
    members: [
      { id: 'v1', name: 'Sharmin Nahar', avatar: '👩‍🌙', class: 'class12', lastActive: 'এইমাত্র', streak: 32, role: 'captain' },
      { id: 'v2', name: 'Arafat Hossain', avatar: '👨‍🌙', class: 'class12', lastActive: '১৫ মিনিট আগে', streak: 27, role: 'member' },
      { id: 'v3', name: 'Khadija Islam', avatar: '👩‍🔬', class: 'class12', lastActive: '৪৫ মিনিট আগে', streak: 24, role: 'member' },
      { id: 'v4', name: 'Masud Rana', avatar: '👨‍🔬', class: 'class12', lastActive: '১ ঘন্টা আগে', streak: 19, role: 'member' },
      { id: 'v5', name: 'Sumi Akter', avatar: '👩‍💻', class: 'class12', lastActive: '২ ঘন্টা আগে', streak: 15, role: 'member' },
      { id: 'v6', name: 'Ripon Ahmed', avatar: '🧑‍🔬', class: 'class12', lastActive: '৩ ঘন্টা আগে', streak: 22, role: 'member' },
    ],
    activity: [
      { id: 'n1', memberId: 'v1', memberName: 'Sharmin Nahar', avatar: '👩‍🌙', type: 'join_me', content: 'রাত ১০টায় Physics MCQ marathon শুরু — সবাই ready?', subject: 'physics', timestamp: 'এইমাত্র', reactions: 14 },
      { id: 'n2', memberId: 'v2', memberName: 'Arafat Hossain', avatar: '👨‍🌙', type: 'completed', content: 'আজকে ৮০টি Chemistry MCQ শেষ — ৭২/৮০ সঠিক 💪', subject: 'chemistry', timestamp: '১৫ মিনিট আগে', reactions: 17 },
      { id: 'n3', memberId: 'v4', memberName: 'Masud Rana', avatar: '👨‍🔬', type: 'stuck', content: 'Organic reaction mechanism এর sequence মনে রাখতে পারছি না', subject: 'chemistry', timestamp: '১ ঘন্টা আগে', reactions: 5 },
      { id: 'n4', memberId: 'v3', memberName: 'Khadija Islam', avatar: '👩‍🔬', type: 'studied', content: 'জেনেটিক্স + বিবর্তন — দুটো অধ্যায় আজ শেষ', subject: 'biology', timestamp: '৩ ঘন্টা আগে', reactions: 11 },
      { id: 'n5', memberId: 'v6', memberName: 'Ripon Ahmed', avatar: '🧑‍🔬', type: 'joined', content: 'এই গ্রুপে যোগ দিলাম — BUET-এর স্বপ্ন পূরণ করব', timestamp: 'গতকাল', reactions: 9 },
    ],
  },
];
